run:
	ALLOWED_HOSTS=http://localhost:3000, AUTH_GITHUB_ATTRIBUTES=email:email,avatar_url:avatar_url AUTH_GITHUB_CSEC=bc36528b350b0623da2706f85fe5e068aba1e45f AUTH_GITHUB_CID=f1e72a27597cf66c1e52 go run  app/main.go server --api-url=http://localhost:8080
