run:
	DATASTORE_PASSWORD=, DATASTORE_USERNAME=, DATASTORE_HOST=localhost:5432, ALLOWED_HOSTS=http://localhost:3000, AUTH_GITHUB_ATTRIBUTES=email:email,avatar_url:avatar_url AUTH_GITHUB_CSEC= AUTH_GITHUB_CID= go run  app/main.go server --api-url=http://localhost:8080
