CREATE TABLE IF NOT EXISTS api.users (
    id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    dob TIMESTAMP,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    avatar_url VARCHAR(255),
    primary_type VARCHAR(255) NOT NULL DEFAULT 'customer',
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS api.addresses (
    id VARCHAR(255) PRIMARY KEY,
    city VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    zip INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES api.users (id)
);