# syntax=docker/dockerfile:1

FROM migrate/migrate:v4.15.2

COPY ./migration /migrations

LABEL org.opencontainers.image.authors="vzaiets <vzaets.dev@gmail.com>" \
      org.opencontainers.image.description="freehands migration" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.source="https://github.com/VladimirZaets/freehands.git" \
      org.opencontainers.image.title="freehands migration" \
      org.opencontainers.image.url="https://freehands.com/" \
      org.opencontainers.image.revision="${GITHUB_SHA}"
