docker-migrate:
	docker-compose -f compose-private.yml run --rm app migrate

#docker run --network host migrator -path=/migrations/ -database="postgres://freehands:freehands@localhost:5432/freehands?sslmode=disable&search_path=api" down
