# syntax=docker/dockerfile:1

FROM mailhog/mailhog

LABEL org.opencontainers.image.authors="vzaiets <vzaets.dev@gmail.com>" \
      org.opencontainers.image.description="freehands database" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.source="https://github.com/VladimirZaets/freehands.git" \
      org.opencontainers.image.title="freehands database" \
      org.opencontainers.image.url="https://freehands.com/" \
      org.opencontainers.image.revision="${GITHUB_SHA}"

EXPOSE 1025
EXPOSE 8025